In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_diabetes

In [2]:
x, y = load_diabetes(return_X_y=True)
x

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [3]:
x_train, x_test, y_train, y_test = train_test_split(x,y,random_state=2, test_size=0.2)

In [4]:
lr = LinearRegression()

In [5]:
lr.fit(x_train, y_train)

LinearRegression()

In [6]:
y_pred =lr.predict(x_test)

In [7]:
r2_score(y_test,y_pred )

0.4399338661568968

In [8]:
import random
class MGD:
  def __init__(self, batch_size, learning_rate, epoch):
    self.batch_size = batch_size
    self.epoch= epoch
    self.learning_rate = learning_rate
    self.coef_ = None
    self.intercept_ = None

  def fit(self, x_train, y_train):
    self.intercept_ = 0
    self.coef_ = np.ones(x_train.shape[1])

    for i in range(self.epoch):
      for j in range(int(x_train.shape[0]/self.batch_size)):
        idx = random.sample(range(x_train.shape[0]),self.batch_size)

        y_hat = np.dot(x_train[idx],self.coef_) + self.intercept_

        intercept_der = -2 * np.mean(y_train[idx] - y_hat)
        self.intercept_ = self.intercept_ - (self.learning_rate * intercept_der)

        coef_der = -2 * np.dot((y_train[idx] - y_hat),x_train[idx])
        self.coef_ = self.coef_ - (self.learning_rate * coef_der)

    print(self.intercept_,self.coef_)

  def predict(self,X_test):
        return np.dot(x_test,self.coef_) + self.intercept_

In [9]:
mbr = MGD(batch_size=int(x_train.shape[0]/50),learning_rate=0.01,epoch=100)

In [10]:
mbr.fit(x_train,y_train)

152.93077254094234 [  25.2658837  -134.28804086  451.51512196  307.7875929   -22.47201441
  -87.19802    -191.44261628  115.32720914  403.2334777   111.54389306]


In [11]:
y_pred = mbr.predict(x_test)

In [12]:
r2_score(y_test,y_pred)

0.4528706858092263

In [13]:
from sklearn.linear_model import SGDRegressor

In [14]:
sgd = SGDRegressor(learning_rate='constant',eta0=0.1)
batch_size = 35

for i in range(100):

    idx = random.sample(range(x_train.shape[0]),batch_size)
    sgd.partial_fit(x_train[idx],y_train[idx])
sgd.coef_

array([  58.46939757,  -68.22264576,  359.01004771,  225.74949476,
         -7.73412862,  -32.68800185, -201.53283719,  137.75697066,
        301.24180046,  122.0991313 ])

In [15]:
sgd.intercept_

array([135.8049563])

In [16]:
y_pred = sgd.predict(x_test)

In [17]:
r2_score(y_test,y_pred)

0.3917925721053299